husky install folder changed 2

diff --git a/Project/backend/.husky/pre-commit b/Project/backend/.husky/pre-commit
--- a/Project/backend/.husky/pre-commit
+++ b/Project/backend/.husky/pre-commit
@@ -4,14 +4,14 @@
 echo '🏗️👷 Hi, my name is LuciferX. I am responsible for testing your project before commit'
 
 # Check Prettier standards
-yarn check-format ||
+cd Project/backend && yarn check-format ||
 (
-  echo '🤢🤮 Prettier Check Failed. Your code styling not looking good. 🤢🤮  Run npm run format, add changes and try commit again.';
+  echo '🤢🤮 Prettier Check Failed. Your code styling not looking good. 🤢🤮  Run yarn fix-format, add changes and try commit again.';
   false;
 )
 
 # Check ESLint Standards
-yarn check-lint ||
+cd Project/backend && yarn check-lint ||
 (
   echo '😤🏀 ESLint Check Failed. Your code may have some linting issues. 👋😤 Make the required changes listed above, add changes and try to commit again.'
   false; 
